spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: usr
    password: usr
    url: jdbc:h2:file:./db/out
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
#Back in 1922
logging:
  level:
    org.springframework.web.servlet.PageNotFound: error
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: warn
    liquibase.executor.jvm.JdbcExecutor: warn
    springfox: warn
    root: info